application: foleo-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: .*
  script: main.app
